// src/lib/components/Footer.svelte
<script>
	import { categories, categoriesNames } from '$lib/categories';
	import { page } from '$app/state';
</script>

<footer
	class="
		footer-text bottom-0 z-[-1] w-full bg-black p-6 font-display
		not-[:has(:focus-visible)]:sticky
		md:p-12
		dark:bg-sandy
	"
>
	<div
		class="
			flex flex-col
			md:flex-row md:items-end
		"
	>
		<div
			class="
				flex flex-col text-2xl font-semibold break-all
				md:mt-0 md:gap-1.5 md:pr-36 md:text-3xl
				tall-screen:mt-2 tall-screen:gap-3 tall-screen:text-4xl
			"
		>
			{#each categories as category (category)}
				<a
					href={'/?category=' + category + '#posts'}
					class={[
						'w-fit',
						{
							'text-active dark:text-active-dark':
								category && category === page.url.searchParams.get('category')
						}
					]}
				>
					{categoriesNames[category]}
				</a>
			{/each}
		</div>
		<div
			class="
				mt-4 flex flex-1 flex-col gap-1 font-caption font-medium
				md:mt-0 md:px-4 md:text-base
				tall-screen:mt-8 tall-screen:text-xl
			"
		>
			<span>My socials:</span>
			<a href="https://github.com/VityaSchel" class="link">GitHub</a>
			<a href="https://instagram.com/vityaczech" class="link">Instagram</a>
			<a href="https://www.linkedin.com/in/hloth/" class="link">Linkedin</a>
			<a href="https://github.com/VityaSchel/blog.hloth.dev" class="link mt-3">
				This website is open source
			</a>
		</div>
		<div
			class="
				mt-4 flex flex-col gap-1 text-sm font-medium
				md:mt-0 md:items-end md:justify-end md:text-right md:text-sm
				tall-screen:mt-8 tall-screen:text-lg
			"
		>
			<span>Contact me:</span>
			<a class="link" href="https://matrix.to/#/@hloth:hloth.dev">Matrix</a>
			<a class="link" href="mailto:hi@hloth.dev">hi@hloth.dev</a>
			<a class="link" href="mailto:jobs@hloth.dev">jobs@hloth.dev</a>
		</div>
	</div>
	<hr
		class="
			mt-5 h-[2px] w-full border-none bg-white
			sm:mt-[41px]
			dark:bg-black
		"
	/>
	<div class="mt-3 flex flex-wrap justify-between gap-x-2">
		<span class="block font-medium">/2024/2025</span>
		<span
			class="
				block text-sm font-medium tracking-normal text-inverted-alt
				dark:text-inverted-alt-dark
			"
		>
			Licensed with <a
				class="border-b-[1px]"
				href="https://github.com/VityaSchel/blog.hloth.dev/tree/main/LICENSE"
				target="_blank"
				rel="nofollow noreferrer noopener"
			>
				MIT
			</a>
			unless otherwise stated.
		</span>
	</div>
</footer>

<style lang="postcss">
	@reference 'tailwindcss';
	.link {
		@apply w-fit underline underline-offset-4;
	}
</style>

// src/widgets/common/footer.tsx
import { categories } from '@/shared/model/category'
import React from 'react'
import { useTranslation } from 'next-i18next'
import { FocusableFooterLink } from '@/features/focusable-footer-link'

export function Footer() {
  const { t } = useTranslation()

  React.useEffect(() => {
    const onScroll = () => {
      if(window.scrollY + window.innerHeight >= Math.max(document.body.scrollHeight - 200, 1)) {
        window.document.body.classList.add('no-overscroll')
      } else {
        window.document.body.classList.remove('no-overscroll')
      }
    }

    window.addEventListener('scroll', onScroll)
    return () => {
      window.removeEventListener('scroll', onScroll)
    }
  }, [])

  return (
    <footer className='bg-text w-full footer-text sticky z-0 bottom-0 p-6 md:p-12 font-display'>
      <div className='flex flex-col md:flex-row md:items-end'>
        <div className='flex flex-col gap-3 md:gap-1.5 font-medium text-4xl md:text-3xl w-24 flex-[25%] max-w-[25%] pr-4'>
          {categories.map((category) => (
            <FocusableFooterLink
              href={'/?category=' + category + '#posts'}
              shallow={true}
              key={category}
              className='w-fit'
            >
              {t(`categories.${category}`)}
            </FocusableFooterLink>
          ))}
        </div>
        <div className='flex-1 flex flex-col gap-1 mt-8 md:mt-0 md:px-4 text-2xl md:text-base'>
          <FocusableFooterLink href='https://github.com/VityaSchel' className='font-medium w-fit'>GitHub</FocusableFooterLink>
          <FocusableFooterLink href='https://instagram.com/vityaczech' className='font-medium w-fit'>Instagram</FocusableFooterLink>
          <FocusableFooterLink href='https://t.me/hlothdev' className='font-medium w-fit'>Telegram</FocusableFooterLink>
          <FocusableFooterLink href='https://www.linkedin.com/in/hloth/' className='font-medium w-fit'>Linkedin</FocusableFooterLink>
        </div>
        <div className='flex flex-col mt-4 md:mt-0 md:items-end md:justify-end gap-1 md:text-right'>
          <span className='text-xl md:text-xs font-medium'>{t('footer.contact_me')}:</span>
          <span className='text-xl md:text-xs font-medium'>hi@hloth.dev</span>
          <span className='text-xl md:text-xs font-medium'>jobs@hloth.dev</span>
        </div>
      </div>
      <hr className='w-full h-[2px] border-none bg-inverted mt-[41px]' />
      <div className='flex justify-between'>
        <span className='mt-3 block font-medium'>/2024</span>
        <span className='mt-3 block text-sm text-[var(--text-inverted-alt)]'>Licensed with CC0 (Public domain)</span>
      </div>
    </footer>
  )
}
