// src/routes/[id=postid]/edit/BannerUploader.svelte
<script lang="ts">
	import { mediaFileIdSchema } from "$lib/media";
	import { z } from "zod";

	let {
		value = $bindable(),
		alt = $bindable(),
		disabled = false,
	}: {
		value: string | null;
		alt: string;
		disabled?: boolean;
	} = $props();

	let img: string | null = $derived(value ? `/files/${value}` : null);

	let progress = $state(0);
	let uploading = $state(false);

	let fileSelector: HTMLInputElement;
</script>

<div
	class="banner-clip md:banner-clip-lg relative aspect-[1.625/1] max-w-[40%]
		flex-[40%] overflow-clip"
>
	<span
		class="absolute top-6 right-6 z-1 rounded-md bg-black/50 px-1.5 text-white"
	>
		1625x1000
	</span>
	<button
		class="absolute top-0 left-0 z-10 h-full w-full cursor-pointer
			bg-transparent focus-visible:outline-2"
		{disabled}
		onclick={() => fileSelector.click()}
		aria-label="Upload banner image"
	></button>
	<input
		type="file"
		accept="image/*"
		onchange={(e) => {
			const file = e.currentTarget.files?.[0];
			if (file) {
				const reader = new FileReader();
				reader.onload = () => {
					img = reader.result as string;
				};
				reader.readAsDataURL(file);

				uploading = true;
				const formData = new FormData();
				formData.append("image", file);
				progress = 0;
				const xhr = new XMLHttpRequest();
				xhr.open("POST", "/api/media?remote=false&type=image&crop=banner");
				xhr.upload.onprogress = (event) =>
					(progress = event.loaded / event.total);
				xhr.onload = () => {
					try {
						if (xhr.status === 200) {
							value = z
								.object({
									success: z.literal(1),
									file: z.object({
										id: mediaFileIdSchema,
									}),
								})
								.parse(JSON.parse(xhr.responseText)).file.id;
						} else {
							img = null;
							fileSelector.value = "";
						}
					} catch (error) {
						console.error("Error parsing response:", error);
					} finally {
						uploading = false;
					}
				};
				xhr.send(formData);
			}
		}}
		class="hidden"
		bind:this={fileSelector}
		tabIndex={-1}
	/>
	{#if img}
		<img src={img} class="h-full w-full object-cover" {alt} />
		<input
			type="text"
			class={[
				`
					hover border-text absolute right-14 bottom-2 left-14 z-10 rounded-md border
					bg-white p-2 opacity-0 shadow-lg transition-opacity
					hover:opacity-100
					focus:opacity-100 focus:outline-none
					dark:bg-black-alt
				`,
			]}
			onclick={(e) => e.stopPropagation()}
			placeholder="[alt]"
			bind:value={alt}
			maxLength={1024}
		/>
	{:else}
		<div class="bg-placeholder h-full w-full"></div>
	{/if}
	<div
		class={[
			"absolute bottom-0 left-0 z-10 h-[4px] bg-blue-700 transition-opacity",
			{
				"opacity-1": uploading,
				"opacity-0": !uploading,
			},
		]}
		style="width: {(progress / 0.8 + 0.1) * 100}%"
	></div>
</div>

<style>
	.bg-placeholder {
		background-color: #e5e5f7;
		opacity: 0.8;
		background-image: radial-gradient(#444cf7 0.5px, #e5e5f7 0.5px);
		background-size: 10px 10px;
	}
</style>

// src/features/banner-uploader.tsx
import React from 'react'
import cx from 'classnames'

export function BannerUploader({ value, onChange, alt, altOnChange, disabled, bannerAltShow }: {
  value: string
  onChange: (banner: { src: string, placeholder: string, width: number, height: number }) => void
  alt: string
  altOnChange: (alt: string) => void
  disabled: boolean
  bannerAltShow: boolean
}) {
  const [banner, setBanner] = React.useState(value)
  const [progress, setProgress] = React.useState(0)
  const [uploading, setUploading] = React.useState(false)

  const bannerFileSelectorRef = React.useRef<HTMLInputElement>(null)
  const handleUploadBanner = () => {
    bannerFileSelectorRef.current?.click()
  }
  const uploadBanner = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.currentTarget.files?.[0]
    if (file) {
      const reader = new FileReader()
      reader.onload = () => {
        setBanner(reader.result as string)
      }
      reader.readAsDataURL(file)

      setUploading(true)
      const formData = new FormData()
      formData.append('file', file)
      setProgress(0)
      const xhr = new XMLHttpRequest()
      xhr.open('POST', '/api/upload-media')
      xhr.upload.onprogress = (event) => {
        setProgress(event.loaded / event.total)
      }
      xhr.onload = () => {
        if (xhr.status === 200) {
          const response = JSON.parse(xhr.responseText)
          onChange({
            src: response.file.url,
            placeholder: response.file.placeholder,
            width: response.file.width,
            height: response.file.height
          })
        } else {
          setBanner('')
          bannerFileSelectorRef.current!.value = ''
        }
        setUploading(false)
      }
      xhr.send(formData)
    }
  }

  React.useEffect(() => {
    setBanner(value)
  }, [value])

  return (
    <div
      className='rounded-[60px] relative aspect-[1.625/1] flex-[40%] max-w-[40%] overflow-clip'
    >
      <button 
        className='bg-transparent w-full h-full absolute top-0 left-0 focus-visible:outline-2 rounded-[60px] z-10'
        disabled={disabled}
        onClick={handleUploadBanner}
      />
      <input
        type='file'
        accept='image/*'
        onChange={uploadBanner}
        className='hidden'
        ref={bannerFileSelectorRef}
        tabIndex={-1}
      />
      {banner ? (<>
        <img src={banner} className='w-full h-full object-cover' />
        <input 
          type='text' 
          className={cx('absolute bottom-2 left-14 right-14 shadow-lg rounded-md p-2 hover opacity-0 hover:opacity-100 transition-opacity border border-text focus:outline-none focus:opacity-100 z-10', {
            'opacity-100': bannerAltShow
          })}
          onClick={(event) => event.stopPropagation()}
          placeholder='[alt]'
          value={alt}
          onChange={(event) => altOnChange(event.currentTarget.value)}
          maxLength={1024}
        />
      </>
      ) : (
        <div className='bg-placeholder w-full h-full' />
      )}
      <div
        className={cx('h-[4px] bg-blue-700 z-10 absolute bottom-0 left-0 transition-opacity', {
          'opacity-1': uploading,
          'opacity-0': !uploading
        })}
        style={{ width: ((progress / 0.8) + 0.1) * 100 + '%' } as React.CSSProperties}
      />
    </div>
  )
}
