// src/routes/Posts.svelte
<script lang="ts">
	import PostPreview from '$lib/components/PostPreview.svelte';
	import Separator from '$lib/ui/Separator.svelte';
	import NoPostsYet from './NoPostsYet.svelte';
	import type { Image } from '$lib/media';
	import type { Category } from '$lib/server/db/schema';

	let {
		posts,
		category,
		drafts = false
	}: {
		posts: {
			id: string;
			title: string;
			banner: Image;
			bannerAlt: string;
			excerpt: string;
			readTime: number;
			createdAt: number;
			category: Category;
			draft?: boolean;
		}[];
		category?: boolean;
		drafts?: boolean;
	} = $props();
</script>

<a id="posts" href="#posts" aria-hidden="true" tabindex={-1}></a>
<section class={{ 'mt-[60px]': !drafts }}>
	{#if posts.length}
		{#each posts as post, i (i)}
			{@const {
				id,
				banner,
				bannerAlt,
				title,
				excerpt,
				readTime,
				createdAt,
				category
			} = post}
			<PostPreview
				{id}
				{banner}
				{bannerAlt}
				{title}
				{excerpt}
				{readTime}
				date={new Date(createdAt)}
				{category}
				first={i === 0}
			/>
			{#if i !== posts.length - 1}
				<Separator />
			{/if}
		{/each}
		{#if category}
			<div class="mt-24 flex justify-center">
				<a
					href="/#posts"
					class="rounded-full border px-4 text-base font-medium"
				>
					Показать всё
				</a>
			</div>
		{/if}
	{:else}
		<NoPostsYet />
	{/if}
</section>

// src/widgets/homepage/posts.tsx
import React from 'react'
import { PostPreview } from '@/features/post-preview'
import { categories } from '@/shared/model/category'
import type { Post } from '@/shared/model/post'
import { Separator } from '@/shared/ui/separator'
import { useRouter } from 'next/router'
import { NoPostsYet } from '@/entities/no-posts-yet'
import cx from 'classnames'
import Link from 'next/link'

export function Posts({ posts, drafts = false }: {
  posts: Post[]
  drafts?: boolean
}) {
  const [filteredPosts, setFilteredPosts] = React.useState(posts)
  const router = useRouter()

  React.useEffect(() => {
    const onUrlChange = () => {
      const category = new URL(window.location.href).searchParams.get('category')
      if (category && categories.includes(category as any)) {
        setFilteredPosts(posts.filter(post => post.category === category))
      } else {
        setFilteredPosts(posts)
      }
    }
    window.addEventListener('popstate', onUrlChange)
    router.events.on('routeChangeComplete', onUrlChange)
    onUrlChange()
    return () => {
      window.removeEventListener('popstate', onUrlChange)
      router.events.off('routeChangeComplete', onUrlChange)
    }
  }, [router, posts])

  return (
    <>
      <a id='posts'></a>
      <section className={cx({ 'mt-[60px]': !drafts })}>
        {filteredPosts.length ? (<>
          {filteredPosts.map((post, i) => (
            <React.Fragment key={post.slug}>
              <PostPreview
                key={post.slug}
                {...post}
                first={i === 0}
                draft={drafts}
              />
              {i !== filteredPosts.length - 1 && <Separator />}
            </React.Fragment>
          ))}
          {router.query.category && (
            <div className='flex justify-center mt-24'>
              <Link 
                href='/#posts' 
                className='text-base border rounded-full px-4 font-medium' 
                scroll={false}
              >
                Показать всё
              </Link>
            </div>
          )}
        </>) : (
          <NoPostsYet />
        )}
      </section>
    </>
  )
}
