// src/entities/category.tsx
import { GeistMono } from 'geist/font/mono'
import { useTranslation } from 'next-i18next'
import cx from 'classnames'

export function Category({ children, className }: {
  children: string
  className?: string
}) {
  const { t } = useTranslation()

  return (
    <span className={cx(className, GeistMono.className, 'uppercase tracking-wide border border-text rounded-md w-fit px-4 py-1.5 text-sm')}>
      {t(`categories.${children}`)}
    </span>
  )
}

// src/lib/components/Category.svelte
<script lang="ts">
	import { categoriesNames, type CategoryValue } from '$lib/categories';

	let {
		category
	}: {
		category: CategoryValue;
	} = $props();
</script>

<span
	class="
		border-text w-fit rounded-md border px-3 py-1.5 font-mono text-xs
		tracking-wide uppercase
	"
>
	{categoriesNames[category]}
</span>
