// src/features/menu.tsx
import React from 'react'
import { useTranslation } from 'next-i18next'
import cx from 'classnames'
import Link from 'next/link'
import { useHotkeys } from 'react-hotkeys-hook'
import { CloseMenuButton } from '@/entities/close-menu-button'
import FocusTrap from 'focus-trap-react'

export function Menu() {
  const { t } = useTranslation('common')
  const [open, setOpen] = React.useState(false)
  useHotkeys('esc', () => open && setOpen(false), [open])

  React.useEffect(() => {
    if(open) {
      document.body.classList.add('menu-open')
    } else {
      document.body.classList.remove('menu-open')
    }
  }, [open])

  return (
    <>
      <button 
        className='bg-[var(--menu-bg)] rounded-full text-inverted pt-[3px] pb-[2px] w-[84px] text-[14px] tracking-[-.03em]'
        onClick={() => setOpen(!open)}
      >
        {t('menu.button')}
      </button>
      <FocusTrap active={open}>
        <div 
          className={cx('fixed w-full h-full top-0 left-0 z-10 transition-blur', {
            'pointer-events-none': !open
          })} 
          style={{ '--blur': open ? '20px' : '0px' } as React.CSSProperties}
          onClick={(e) => {
            if(e.target !== e.currentTarget) return
            setOpen(false)
          }}
        >
          <div className={cx('bg-black text-white w-96 h-full right-0 absolute transition-transform duration-500 menu-bg flex flex-col gap-4 p-8 font-display text-4xl font-bold', {
            'transform translate-x-full': !open,
            'transform-none': open
          })}>
            <CloseMenuButton
              onClose={() => setOpen(false)}
            />
            <Link href='https://hloth.dev/me' className='hover:text-neutral-300 transition-all hover:tracking-wide'>
              {t('menu.about_me')}
            </Link>
            <Link href='https://hloth.dev/portfolio' className='hover:text-neutral-300 transition-all hover:tracking-wide'>
              {t('menu.my_portfolio')}
            </Link>
            <div className='mt-auto flex items-center justify-between text-sm text-gray leading-none'>
              <span className='font-medium'>{t('menu.contact')}:</span>
              <span className='font-normal'>hi@hloth.dev</span>
            </div>
          </div>
        </div>
      </FocusTrap>
    </>
  )
}

// src/lib/components/Menu.svelte
<script lang="ts">
	import { trapFocus } from 'trap-focus-svelte';
	import CloseMenuButton from '$lib/components/CloseMenuButton.svelte';
	import PushNotificationsSwitch from '$lib/components/PushNotificationsSwitch.svelte';
	import { shameCorner } from '$lib/shame-corner.svelte';

	let open = $state(false);
	let closing = $state(false);
</script>

<button
	class="
		w-[84px] cursor-pointer rounded-full bg-black pt-[3px] pb-[2px] text-[14px]
		tracking-[-.03em] text-white
		dark:bg-white dark:text-black
	"
	onclick={() => {
		open = !open;
		closing = false;
	}}
>
	Menu
</button>
<div
	class={[
		'transition-blur fixed top-0 left-0 z-10 h-full w-full',
		{
			'pointer-events-none': !open
		}
	]}
	style="--blur: {open ? 20 : 0}px; transition-duration: {shameCorner.safari
		? '2000ms'
		: '500ms'};"
	use:trapFocus
	inert={!open}
>
	<button
		onclick={(e) => {
			if (e.target !== e.currentTarget) return;
			open = false;
		}}
		class="absolute top-0 left-0 h-full w-full"
		aria-label="Close menu"
		tabindex="-1"
	></button>
	<div
		class={[
			`
				menu-bg absolute right-0 flex h-full w-96 max-w-full flex-col bg-black py-8
				font-display text-4xl font-bold text-white transition-transform ease-in-out
			`,
			{
				'duration-500': !shameCorner.safari,
				'duration-2000': shameCorner.safari,
				'translate-x-full transform': !open,
				'transform-none': open
			}
		]}
	>
		<CloseMenuButton bind:closing onClose={() => (open = false)} />
		{#snippet link(label: string, href: string)}
			<a
				{href}
				class="
					px-8 py-2 transition-[letter-spacing,color]
					focus:outline-0
					focus-visible:bg-blue-400/20
					hf:tracking-wide hf:text-neutral-300
				"
			>
				{label}
			</a>
		{/snippet}
		{@render link('About Me', 'https://hloth.dev/me')}
		{@render link('My Portfolio', 'https://hloth.dev/portfolio')}
		<div class="mt-auto w-full px-8">
			<PushNotificationsSwitch />
		</div>
		<div
			class="
				mt-4 flex items-center justify-between px-8 text-sm leading-none
				text-[#a3a3a3]
				dark:text-[#4b5563]
			"
		>
			<span class="font-medium">Contact me:</span>
			<span class="font-normal">hi@hloth.dev</span>
		</div>
	</div>
</div>
